openapi: 3.0.3
info:
  title: Test security schema with x-session
  version: 1.0.0
paths:
  /test:
    get:
      responses:
        204:
          description: OK
      security:
      - test_auth: []
components:
  securitySchemes:
    test_auth:
      type: http
      scheme: basic
      x-session: false
